- src/zh/guide/geminiql/functions.md
Complete the description of some aggregate functions in the functions document
> chore: add functions doc

- src/guide/quick_start/get_started.md
I have translated the file get_started into English. Please check whether the translation is correct or not. Thanks a lot!
> get_started English version

- src/guide/write/line_protocol.md
- src/zh/guide/write/line_protocol.md
> docs: fix English word

- src/guide/manage/configurations.md
- src/guide/manage/syscontrl_cmd.md
Add the syscontrl command description
> docs: add the syscontrl command description

- src/zh/guide/geminiql/sql_syntax/DDL/create_measurement.md
> chore: update create_measurement.md

- src/zh/guide/geminiql/sql_syntax/DML/text_retrieval.md
descript how to use match、match_phrase、like in openGemini text retrival
> chore(text): add description of text retrieval

- src/.vuepress/components/TCPage.vue
- src/.vuepress/data/TCData.ts
> docs: change SIG release src

- src/zh/guide/security_user/user_manage.md
An error occurs when the command for creating an admin account is executed. The error has been resolved
Signed-off-by: xiangyu5632 <xiangyu5632@126.com>
> fix(user_manage): update src/zh/../user_manage.md

- src/zh/guide/reference/kernel_metrics.md
add kernel_metrics and grafana panel examples
> chore: add kernel_metrics and grafana panel examples

- src/zh/guide/contribution/Document.md
add new document "src/zh/guide/contribution/Document.md"
- Details how to contribute a openGemini's document
> chore: add new document

- src/zh/guide/versions/Release_notes_1.1.md
> chore: add v1.1.0-rc1 release notes

- src/zh/guide/versions/Release_notes_1.1.md
Modified Release_notes_1.1.md，add a new features and some bugfixs
> chore: Update Release_notes_1.1.md

- src/guide/features/continue_query.md
- src/zh/guide/features/continue_query.md
Add both English and Chinese documents for CQ functionality.
> docs: add Chinese and English docs for CQ

- src/zh/guide/features/high_series_cardinality.md
- src/zh/guide/features/query_manage.md
- src/zh/guide/schema/measurement.md
- src/zh/guide/write_data/column_protocol_tutorials.md
add docs about high series cardinality, and query manage, and create table
> chore: update docs about high series cardinality

- src/zh/guide/functions/aggregate.md
- src/zh/guide/reference/gemix_manual.md
- src/zh/guide/schema/measurement.md
- src/zh/guide/schema/schema.md
update documents of schema, measurement, gemix, etc.
> chore: update documents of schema,measurement,gemix etc.

- src/zh/guide/functions/selector.md
update the document of selector functions, such as MAX(), MIN(), TOP(), BOTTOM() etc.
> chore: update selector functions

- src/zh/guide/functions/string.md
update the document of string functions such as STR(), STRLEN(), SUBSTR()
> chore: update the document of string functions

- src/zh/guide/versions/Release_notes_1.2.md
> chore: add v1.2.0 release note

- src/guide/features/stream.md
> chore:update openGemini docs stream

- src/zh/guide/develop/SDK.md
- src/zh/guide/develop/client_go.md
- src/zh/guide/develop/client_java.md
update SDK's documents with the latest development progress
> chore: update sdk documents

- src/zh/guide/develop/SDK.md
- src/zh/guide/develop/client_go.md
- src/zh/guide/develop/client_java.md
- src/zh/guide/features/downsample.md
> chore: update downsample docs

- src/guide/schema/measurement.md
Updated the syntax of `DROP MEASUREMENT` statement.
please ref: https://github.com/openGemini/openGemini/pull/666
> docs: update DROP MEASUREMENT syntax

- src/guide/features/high_series_cardinality.md
- src/guide/schema/measurement.md
- src/zh/guide/features/downsample.md
- src/zh/guide/features/high_series_cardinality.md
- src/zh/guide/schema/measurement.md
add English doc high-series-cardinality-engine.md
1. Add the comparison of features between the high-cardinality storage engine and the default storage engine
> chore: add english doc high-series-cardinality-engine.md

- src/guide/schema/measurement.md
- src/zh/guide/schema/measurement.md
update drop measurement command
1. support delete measurement with a specified retention policy
> chore: update drop measurement command

- src/guide/versions/Release_notes_1.3.md
> chore: update Release_notes_1.3.md

- src/guide/query_data/promql.md
- src/guide/reference/promql_functions.md
- src/guide/versions/Release_notes_1.3.md
- src/zh/guide/query_data/promql.md
- src/zh/guide/reference/promql_functions.md
List the Prometheus functions and operators supported by openGmeini
> chore: list the Prometheus functions and operators supported by openGmeini

- src/zh/guide/maintenance/monitor.md
update the monitor configuration item `store-path`
origion
```
[monitor]
pushers = "file"
store-enabled = true
store-database = "monitor"
store-interval = "10s"
store-path = "/tmp/openGemini/metric/metric.data"
```
current
```
[monitor]
pushers = "file"
store-enabled = true
store-database = "monitor"
store-interval = "10s"
store-path = "/tmp/openGemini/metric/"
```
> chore: update the monitor configuration item

- src/guide/schema/measurement.md
- src/zh/guide/schema/measurement.md
add docs about new command `show measurements detail with measurement=xxx`
> chore: update measurement commands

- src/guide/reference/configurations.md
- src/zh/guide/reference/configurations.md
add some descriptions about configs in new record write service, ref https://github.com/openGemini/openGemini/pull/790
> docs: add configs about record write service

- src/zh/guide/features/downsample.md
- src/zh/guide/versions/Release_notes_1.3.1.md
Modify the docs for `downsample` feature
> chore: modify the docs for downsample

- src/.vuepress/utils/getFooter.ts
resolve https://github.com/openGemini/openGemini.github.io/issues/148
> chore: update current date

- src/zh/guide/deploy_cluster/deploy_cluster_manual.md
tsbs commands have something wrong; this PR is fixed
> chore: update tsbs test commands

- src/guide/quick_start/docker.md
> docs: using correct image tag
